#ifndef CONSTANTS_H_
#define CONSTANTS_H_

// Define size and origin for the playing field
#define GAMEWINDOW_X 0
#define GAMEWINDOW_Y 0

#define BACKDROP_STARCOUNT 100

// Hexgrid setup
#define HEXTILE_SIZE 20
#define HEXTILE_SEGMENT_SIZE HEXTILE_SIZE / 4
#define HEXGRID_ROWS 15
#define HEXGRID_COLS 15
#define HEXTILE_PAWNSIZE 18

#define GAMEMECHANICS_MAXTILEMOVERANGE 4
#define GAMEMECHANICS_MAXTILEPHASERRANGE 4
#define GAMEMECHANICS_MAXTILETORPEDORANGE 5


#define GAME_FORM 1000

#endif