#!/usr/bin/env python3
"""Bakes the real game art (resources/ships, resources/others,
resources/others_noresize) into a C header of RGB565 + alpha pixel arrays,
keyed by the same numeric GFX_RES_* ids the Palm OS backend uses (read from
resources/graphicResources.map, the same source of truth
generateResourceFile.sh uses to build the Palm .rcp/.h).

This mirrors generateBitmaps.sh's job (rotate each ship into 8 frames, mask
the tile highlight hexagons) but bakes straight into a wasm-compatible C
array instead of Palm .bmp files, since the web build has no Palm resource
compiler to run.

Run from the repository root: python3 sauce/platform/web/generate_web_assets.py
"""
import os
import re
import sys

from PIL import Image, ImageDraw

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
MAP_FILE = os.path.join(ROOT, "resources", "graphicResources.map")
SHIPS_DIR = os.path.join(ROOT, "resources", "ships")
OTHERS_DIR = os.path.join(ROOT, "resources", "others")
OTHERS_NORESIZE_DIR = os.path.join(ROOT, "resources", "others_noresize")
OUT_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "web_assets_generated.h")

MAX_DIMENSION = 48

TILE_COLORS = {
    "tilefeatured": "#3498db",
    "tileattack": "#e74c3c",
    "tilemove": "#2ecc71",
    "tilewarn": "#f1c40f",
}
TILE_SIZE = 20

SHIP_FRAME_RE = re.compile(r"^(ship[abcd])_(\d+)$")


def load_image(name):
    """Same source-file resolution order generateBitmaps.sh uses for an
    individual (non-ship) image: resources/others, then
    resources/others_noresize."""
    for directory in (OTHERS_DIR, OTHERS_NORESIZE_DIR):
        path = os.path.join(directory, name + ".png")
        if os.path.isfile(path):
            return Image.open(path).convert("RGBA")
    return None


def tile_hex_image(color_hex, size):
    """Replicates resources/generateTileBitmap.sh: a flat-colored hexagon
    (pointed top/bottom) cut out of a square, used for the move/attack/warn/
    featured tile highlight overlays."""
    img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    segment = size // 4
    points = [
        (size / 2, 0),
        (0, segment),
        (0, size - segment),
        (size / 2, size),
        (size, size - segment),
        (size, segment),
    ]
    r = int(color_hex[1:3], 16)
    g = int(color_hex[3:5], 16)
    b = int(color_hex[5:7], 16)
    draw.polygon(points, fill=(r, g, b, 255))
    return img


def ship_frame_image(letter, frame):
    src = Image.open(os.path.join(SHIPS_DIR, "ship%s.png" % letter)).convert("RGBA")
    degrees = frame * 45
    if degrees == 0:
        return src
    return src.rotate(-degrees, resample=Image.BICUBIC, expand=False, fillcolor=(0, 0, 0, 0))


def resolve_image(name):
    ship_match = SHIP_FRAME_RE.match(name)
    if ship_match:
        return ship_frame_image(ship_match.group(1)[-1], int(ship_match.group(2)))
    if name in TILE_COLORS:
        return tile_hex_image(TILE_COLORS[name], TILE_SIZE)
    return load_image(name)


def downscale_if_needed(img):
    w, h = img.size
    largest = max(w, h)
    if largest <= MAX_DIMENSION:
        return img
    scale = MAX_DIMENSION / float(largest)
    return img.resize((max(1, int(w * scale)), max(1, int(h * scale))), Image.LANCZOS)


def to_rgb565(r, g, b):
    return ((r >> 3) & 0x1F) << 11 | ((g >> 2) & 0x3F) << 5 | ((b >> 3) & 0x1F)


def emit_asset(out, ident, img):
    img = downscale_if_needed(img)
    w, h = img.size
    pixels = img.load()
    colors = []
    alphas = []
    for y in range(h):
        for x in range(w):
            r, g, b, a = pixels[x, y]
            colors.append(to_rgb565(r, g, b))
            alphas.append(255 if a >= 128 else 0)
    out.write("static const unsigned short %s_color[] = {%s};\n" % (ident, ",".join(str(c) for c in colors)))
    out.write("static const unsigned char %s_alpha[] = {%s};\n" % (ident, ",".join(str(a) for a in alphas)))
    return w, h


def main():
    entries = []
    with open(MAP_FILE) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            res_id, name = line.split(";", 1)
            entries.append((int(res_id), name))

    skipped = []
    with open(OUT_FILE, "w") as out:
        out.write("/* GENERATED by generate_web_assets.py from resources/graphicResources.map\n")
        out.write("   and the real game art in resources/ships, resources/others,\n")
        out.write("   resources/others_noresize. Do not edit by hand; re-run the script\n")
        out.write("   after touching any source asset. */\n")
        out.write("#ifndef WEB_ASSETS_GENERATED_H_\n#define WEB_ASSETS_GENERATED_H_\n\n")

        table_rows = []
        for res_id, name in entries:
            img = resolve_image(name)
            if img is None:
                skipped.append(name)
                continue
            ident = "web_asset_%s" % name
            w, h = emit_asset(out, ident, img)
            table_rows.append((res_id, ident, w, h))

        out.write("\ntypedef struct WebAssetEntry {\n")
        out.write("    unsigned short id;\n")
        out.write("    int width;\n")
        out.write("    int height;\n")
        out.write("    const unsigned short *color;\n")
        out.write("    const unsigned char *alpha;\n")
        out.write("} WebAssetEntry;\n\n")
        out.write("static const WebAssetEntry web_assetTable[] = {\n")
        for res_id, ident, w, h in table_rows:
            out.write("    {%d, %d, %d, %s_color, %s_alpha},\n" % (res_id, w, h, ident, ident))
        out.write("};\n\n#endif\n")

    print("Generated %s with %d entries (%d skipped: %s)" % (OUT_FILE, len(table_rows), len(skipped), skipped))


if __name__ == "__main__":
    sys.exit(main())
